새 포스팅 PR입니다.
rgpkorea/rgpkorea.github.io pull request #1
Opened 2018-04-30 09:22 UTC by beomcheol

앞으로 메인 저장소에는 직접 포스팅 못하게 막고

이런식으로 PR을 올려서 검수 단계를 만드는게 어떨까 해서

한번 시범적으로 시행 해 봅니다.

2018-04-30 09:38 UTC, beomcheol commented
띠롱

2018-04-30 09:44 UTC, beomcheol commented
띠로롱

2018-04-30 09:45 UTC, beomcheol reviewed
커멘트 테스트

2018-05-23 03:12 UTC, kucuny approved these changes

2018-05-24 05:08 UTC, rgpnarikim commented on content/posts/blog-making-review.md
> +블로그 사이트는 글 특성상 컨텐츠에 스타일이 포함되어 있습니다. 그렇다는 것은 컨텐츠를 저장소에 저장할 때 단순 텍스트만 저장 할 수는 없다는 것입니다. 속성이 포함된 컨텐츠를 작성하기 위해서는 별도의 텍스트 에디팅이 필요하고 컨텐츠 추가를 위한 기능을 따로 구현해 두어야만 합니다. 게다가 HTML - CSS 로 구성된 스타일은 자칫 글로벌 속성등에 의해
"적성하게" --> 작성하게

2018-05-24 05:16 UTC, rgpnarikim requested changes
흥미롭게 읽었습니다! 저도 PR이란 것을 해보아서 즐거웠어요

2018-05-24 05:16 UTC, rgpnarikim commented on content/posts/blog-making-review.md
> +마크다운을 이용하여 웹 사이트를 구현하려는 방법들이 많이 시도 되었고, 결국엔 Static Website Generator(이하 SWG) 라는 방식이 나오게 되었습니다. 어떻게 보면 url의 주소가 곧 html 파일의 위치가 되는 방식식이 좀 더 구식인듯 보이지만, "Generator"라는 이름이 붙은 만큼 이러한 구조를 직접 구성하는게 아닌, 마크다운
"방식식이" --> 방식이

2018-05-24 05:16 UTC, rgpnarikim commented on content/posts/blog-making-review.md
> +이 방식은 위에서 언급한 dynamic 방식에서 나타나는 유지보수의 어려움과 글 쓰기의 번거로움 등의 단점들을 극복하였고, 또한 호스팅 조차도 별도의 서버 세팅 없이 배교적 매우 간단하게 할 수 있게 되었습니다. 게다가 가장 인기있는 소스코드 저장소인 GitHub에서 제공하는 웹호스팅 서비스인 github page에서 "jekyll"이라는 SWG를 공식적
배교적 --> 비교적

2018-05-24 05:16 UTC, rgpnarikim commented on content/posts/blog-making-review.md
> +github에서는 "jekyll"을 공식 지원 하고 있지만, SWG 세계에는 이외에도 "HUGO"라는것까지 총 두가지의 선두주자가 이끌어 가고 있습니다. 두가지 다 뛰어난 frame work이고 사실 크게 차이가 없지만, 사용성, 테마, 확장성 등의 기준에서 여러가지 장단점들을 비교한 뒤 하나를 선택해 보기로 하였습니다. (사실 저같은 경우 개인 블로그를
"HUGO"라는것까지 --> 띄어쓰기 ""HUGO"라는 것까지

2018-05-24 05:16 UTC, rgpnarikim commented on content/posts/blog-making-review.md
> +테마의 종류는 둘다 우열을 가리기 힘들 정도로 다양하게 준비되어 있습니다. 심지어는 양쪽다 존제하는 테마도 많이 있지요. (제가 회사 기술 블로그 만들기 프로젝트에 중간부터 참여를 했지만 jekyll로 결정된 부분을 변경할 수 있었던 이유도 하고자 했던 테마가 양쪽 다 존제 하고 있었던 점도 크게 작용 했습니다.)
존제하는 --> 존재하는

존제 하고 --> 존재하고

2018-05-24 05:16 UTC, rgpnarikim commented on content/posts/blog-making-review.md
> +개인 블로그가 아닌 회사의 블로그를 만드는 이상, 테마가 있더라도 있는 그데로 사용할 수는 없었습니다. 기본적인 스타일 변경 뿐 아니라 레이아웃이나 메뉴 갯수 등 많은 부분에 있어서 커스터마이징이 이루어 졌습니다.
그데로 --> 그대로

2018-05-24 05:57 UTC, beomcheol commented
코드리뷰 반영했습니다~ @rgpnarikim 님 approve 해 주세요 ㅋㅋ

2018-05-24 06:23 UTC, rgpnarikim approved these changes

2018-05-24 06:33 UTC, merged